const defaultConfig = require("@wordpress/scripts/config/webpack.config");

// Plugins
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts");

// Utils
const path = require("path");

// Extend wordpress default webpack config
module.exports = {
	...defaultConfig,
	...{
		// Set custom entry points for js and scss
		entry: {
			"js/main": path.resolve(process.cwd(), "src/js", "main.js"),
			"js/editor": path.resolve(process.cwd(), "src/js", "editor.js"),
			"css/main": path.resolve(process.cwd(), "src/scss", "main.scss"),
			"css/editor": path.resolve(
				process.cwd(),
				"src/scss",
				"editor.scss",
			),
		},
		// Add webpack plugins
		plugins: [
			// Include wordpress default plugins
			...defaultConfig.plugins,

			// Remove empty '*.js' files generated by webpack
			new RemoveEmptyScriptsPlugin({
				// Run after wordpress `*.asset.php` files have been generated
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			}),
		],
	},
};
